### ISSUE TITLE
Prettier 2.5.1 issue

### ISSUE THREAD

**Issue by aminya** [atom-community/prettier-config-atomic#20]
### Description

Prettier 2.5.1 adds `value` in the imports with a certain configuration (might be related to Typescript version)

https://stackoverflow.com/a/71043924/7910299

### Steps to Reproduce

1. 
2. 
3. 

**Expected behavior:**

```js
import { something} from './somewhere';
```

**Actual behavior:**

```js
import { value something} from './somewhere';
```

**Reproduces how often:**

**Comment by UziTech** [comment]
is there a repo that this is happening too?
